#ifndef ROVACA_HC_COMMON_ENUM_H_
#define ROVACA_HC_COMMON_ENUM_H_
#include "common/enum.h"

namespace rovaca
{

enum ClippingRepresentation { WRITE_NS = 0, WRITE_Q0S, WRITE_NS_Q0S, SOFTCLIP_BASES, HARDCLIP_BASES, REVERT_SOFTCLIPPED_BASES };

enum VariantType { VT_NO_VARIATION = 0, VT_SNP, VT_MNP, VT_INDEL, VT_SYMBOLIC, VT_MIXED, VT_UNINITIALIZED };

enum GenotypeType { GT_NO_CALL = 0, GT_HOM_REF, GT_HET, GT_HOM_VAR, GT_UNAVAILABLE, GT_MIXED, GT_UNINITIALIZED };

enum GenotypeMergeType { UNIQUIFY = 0, PRIORITIZE, UNSORTED, REQUIRE_UNIQUE };

enum FilteredRecordMergeType { KEEP_IF_ANY_UNFILTERED = 0, KEEP_IF_ALL_UNFILTERED, KEEP_UNCONDITIONAL };

enum OutputMode { EMIT_VARIANTS_ONLY = 0, EMIT_ALL_CONFIDENT_SITES, EMIT_ALL_ACTIVE_SITES };

enum GenotypeAssignmentMethod {
    SET_TO_NO_CALL = 0,
    USE_PLS_TO_ASSIGN,
    USE_POSTERIORS_ANNOTATION,
    SET_TO_NO_CALL_NO_ANNOTATIONS,
    BEST_MATCH_TO_ORIGINAL,
    DO_NOT_ASSIGN_GENOTYPES,
    USE_POSTERIOR_PROBABILITIES,
    PREFER_PLS
};

}  // namespace rovaca

#endif  // ROVACA_HC_COMMON_ENUM_H_
