# Enable address sanitizer (gcc/clang only)
function(enable_sanitizer target_name)
        if(NOT CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang")
                message(FATAL_ERROR "Sanitizer supported only for gcc/clang")
        endif()
        message(STATUS "Address sanitizer enabled")
        target_compile_options(${target_name} PRIVATE -fsanitize=address,undefined)
        target_compile_options(${target_name} PRIVATE -fno-stack-protector)
        target_compile_options(${target_name} PRIVATE -fno-var-tracking)
        target_compile_options(${target_name} PRIVATE -fno-omit-frame-pointer)
        target_compile_options(${target_name} PRIVATE -fsanitize-address-use-after-scope)
        target_link_libraries(${target_name} PRIVATE -fsanitize=address,undefined -fuse-ld=gold)
endfunction()
