# 自动生成 version.h
function(generate_version)
        execute_process(
                COMMAND git rev-list HEAD --count
                OUTPUT_VARIABLE GIT_COMMIT_COUNT
                OUTPUT_STRIP_TRAILING_WHITESPACE)
        execute_process(
                COMMAND git describe --dirty --always --tags
                OUTPUT_VARIABLE GIT_DES
                OUTPUT_STRIP_TRAILING_WHITESPACE)
        execute_process(
                COMMAND git log --format=[sha1]:%H -1
                OUTPUT_VARIABLE GIT_ID_LONG
                OUTPUT_STRIP_TRAILING_WHITESPACE)
        execute_process(
                COMMAND git log --format=[time]:%ci' -1
                OUTPUT_VARIABLE GIT_TIME
                OUTPUT_STRIP_TRAILING_WHITESPACE)
        execute_process(
                COMMAND git log --format=[commit]:%s -1
                OUTPUT_VARIABLE GIT_COMNMIT
                OUTPUT_STRIP_TRAILING_WHITESPACE)
        execute_process(
                COMMAND git log --format=[branch]:%d -1
                OUTPUT_VARIABLE GIT_BRANCH
                OUTPUT_STRIP_TRAILING_WHITESPACE)

        set(VERSION_FILE "version.h")
        set(MAIN_VERSION ${PROJECT_VERSION})

        file(WRITE ${VERSION_FILE} "#ifndef ROVACA_HC_VERSION_H_\n")
        file(APPEND ${VERSION_FILE} "#define ROVACA_HC_VERSION_H_\n")
        file(APPEND ${VERSION_FILE} "\n")
        file(APPEND ${VERSION_FILE} "/* This file is automatically generated, !!!Do not modify!!! */\n")
        file(APPEND ${VERSION_FILE} "\n")
        file(APPEND ${VERSION_FILE} "#define MAIN_VERSION \"${MAIN_VERSION}\"\n")
        file(APPEND ${VERSION_FILE} "#define GIT_DES \"${GIT_DES}\"\n")
        file(APPEND ${VERSION_FILE} "#define GIT_ID_LONG \"${GIT_ID_LONG}\"\n")
        file(APPEND ${VERSION_FILE} "#define GIT_TIME \"${GIT_TIME}\"\n")
        file(APPEND ${VERSION_FILE} "#define GIT_COMNMIT \"${GIT_COMNMIT}\"\n")
        file(APPEND ${VERSION_FILE} "#define GIT_BRANCH \"${GIT_BRANCH}\"\n")
        file(APPEND ${VERSION_FILE} "\n")
        file(APPEND ${VERSION_FILE} "#endif  // ROVACA_HC_VERSION_H_\n")
endfunction()
